---
name: 'gh-actions-docker-compose-up'
description: 'Build and start Docker Compose services with optional Amazon ECR and Docker Hub login.'
inputs:
  docker-hub-username:
    description: Username for Docker Hub login
    default: ''
  docker-hub-access-token:
    description: Access token for Docker Hub login
    default: ''
  aws-region:
    description: AWS region where Amazon ECR is located.
    default: eu-west-1
    required: false
  aws-role-to-assume:
    description: The Amazon Resource Name (ARN) of the role to assume.
    default: 'arn:aws:iam::078810848840:role/GitHub-OIDC-ECR-ReadOnly'
    required: false
  aws-role-session-name:
    description: AWS role session name used for Amazon ECR.
    default: ''
    required: false
  aws-codeartifact-region:
    description: AWS region where AWS CodeArtifact is located.
    default: eu-west-1
    required: false
  aws-codeartifact-role-to-assume:
    description: The Amazon Resource Name (ARN) of the role to assume.
    default: 'arn:aws:iam::078810848840:role/GitHub-OIDC-CodeArtifact-Python-ReadOnly'
    required: false
  aws-codeartifact-role-session-name:
    description: AWS role session name used for AWS CodeArtifact.
    default: ''
    required: false
  service-profiles:
    description: Docker compose service profiles to start
    default: ''
  db-name:
    description: Database name
    default: ''
  apply-migrations:
    description: Set to true to apply migrations
    required: false
    default: 'false'
  working-directory:
    description: The working directory where the commands are run
    required: false
    default: ./
runs:
  using: "composite"
  steps:
    - name: Print versions
      run: |
        echo "::group::Print versions"
        docker version
        docker compose version
        aws --version
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Login to Docker Hub
      if: ${{ inputs.docker-hub-username != '' }}
      run: |
        echo "::group::Login to Docker Hub"
        echo "${DOCKER_HUB_ACCESS_TOKEN}" | \
            docker login --username "${{ inputs.docker-hub-username }}" \
            --password-stdin
        echo "::endgroup::"
      env:
        DOCKER_HUB_ACCESS_TOKEN: ${{ inputs.docker-hub-access-token }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Configure AWS Credentials for Amazon ECR
      if: ${{ inputs.aws-role-session-name != '' }}
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-session-name: ${{ inputs.aws-role-session-name }}
        aws-region: ${{ inputs.aws-region }}
        role-duration-seconds: 900
        output-credentials: true
        output-env-credentials: false
      id: aws-role-credentials-for-ecr-login
    - name: AWS Account ID
      if: ${{ inputs.aws-role-session-name != '' }}
      run: echo "aws-account-id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ steps.aws-role-credentials-for-ecr-login.outputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.aws-role-credentials-for-ecr-login.outputs.aws-secret-access-key }}
        AWS_SESSION_TOKEN: ${{ steps.aws-role-credentials-for-ecr-login.outputs.aws-session-token }}
        AWS_REGION: ${{ inputs.aws-region }}
      id: aws-account-id
    - name: Login to Amazon ECR
      if: ${{ inputs.aws-role-session-name != '' }}
      run: |
        aws ecr get-login-password | \
          docker login --username AWS --password-stdin \
          "${{ steps.aws-account-id.outputs.aws-account-id }}.dkr.ecr.eu-west-1.amazonaws.com"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ steps.aws-role-credentials-for-ecr-login.outputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.aws-role-credentials-for-ecr-login.outputs.aws-secret-access-key }}
        AWS_SESSION_TOKEN: ${{ steps.aws-role-credentials-for-ecr-login.outputs.aws-session-token }}
        AWS_REGION: ${{ inputs.aws-region }}

    - name: Start service containers
      if: ${{ inputs.service-profiles != '' }}
      run: |
        # Start the service containers before building custom container images.
        # This gives the database enough time to start. (At least in our case.)
        echo "::group::Start service containers"
        docker compose up -d
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        COMPOSE_PROFILES: ${{ inputs.service-profiles }}

    - name: Configure AWS Credentials for AWS CodeArtifact
      if: ${{ inputs.aws-codeartifact-role-session-name != '' }}
      uses: aws-actions/configure-aws-credentials@v4.3.1
      with:
        role-to-assume: ${{ inputs.aws-codeartifact-role-to-assume }}
        role-session-name: ${{ inputs.aws-codeartifact-role-session-name }}
        aws-region: ${{ inputs.aws-codeartifact-region }}
        role-duration-seconds: 900
        output-credentials: true
        output-env-credentials: false
      id: codeartifact-credentials
    - name: Build container image
      run: |
        echo "::group::Build container image"
        if [ "${{ steps.codeartifact-credentials.outcome }}" == "success" ]; then
            env \
              AWS_ACCESS_KEY_ID_CODEARTIFACT="${{ steps.codeartifact-credentials.outputs.aws-access-key-id }}" \
              AWS_SECRET_ACCESS_KEY_CODEARTIFACT="${{ steps.codeartifact-credentials.outputs.aws-secret-access-key }}" \
              AWS_SESSION_TOKEN_CODEARTIFACT="${{ steps.codeartifact-credentials.outputs.aws-session-token }}" \
              docker compose build --pull
        else
            docker compose build --pull
        fi
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Create DB
      if: ${{ inputs.db-name != '' }}
      run: |
        # The database containers name must be 'db' and it must be PostgreSQL.
        echo "::group::Create DB"
        docker compose run db psql -h db -U postgres \
            -c "CREATE DATABASE ${{ inputs.db-name }};"
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Apply migrations
      if: ${{ inputs.apply-migrations == 'true' }}
      run: |
        echo "::group::Apply migrations"
        docker compose run web migrate
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Start all containers
      run: |
        echo "::group::Start all containers"
        docker compose up -d
        docker compose logs
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
